import { useEffect, useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { api } from '../../lib/api.js';

const empty = { title:'', message:'', linkLabel:'', linkUrl:'', startsAt:'', endsAt:'' };
export default function AdminPromos() {
  const [items,setItems]=useState([]); const [form,setForm]=useState(empty); const [error,setError]=useState('');
  const load=()=>api.get('/admin/promos').then(r=>setItems(r.data.promos||[]));
  useEffect(()=>{load().catch(e=>setError(e.response?.data?.message||'Could not load promotions'));},[]);
  const add=async e=>{e.preventDefault();setError('');try{await api.post('/admin/promos',{...form,startsAt:form.startsAt||null,endsAt:form.endsAt||null});setForm(empty);await load();}catch(err){setError(err.response?.data?.message||'Could not add promotion');}};
  const toggle=async item=>{try{await api.put(`/admin/promos/${item.id}`,{isActive:!item.isActive});await load();}catch(err){setError(err.response?.data?.message||'Could not update promotion');}};
  const remove=async id=>{if(!window.confirm('Delete this promotion?'))return;try{await api.delete(`/admin/promos/${id}`);await load();}catch(err){setError(err.response?.data?.message||'Could not delete promotion');}};
  return <main className="p-6 lg:p-10"><p className="text-sm uppercase tracking-[0.3em] text-amber-700">Marketing</p><h1 className="font-display text-4xl font-semibold">Promotions</h1><p className="mt-2 text-stone-600">Manage the promo banner content customers see on the store.</p>{error&&<div className="mt-5 rounded-2xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}<div className="mt-8 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><form onSubmit={add} className="rounded-[2rem] bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">New promotion</h2><div className="mt-4 grid gap-3"><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Title" className="rounded-2xl bg-stone-100 px-4 py-3 outline-none"/><textarea required value={form.message} onChange={e=>setForm({...form,message:e.target.value})} placeholder="Promo message" className="min-h-28 rounded-2xl bg-stone-100 px-4 py-3 outline-none"/><div className="grid grid-cols-2 gap-3"><input value={form.linkLabel} onChange={e=>setForm({...form,linkLabel:e.target.value})} placeholder="Button label" className="rounded-2xl bg-stone-100 px-4 py-3 outline-none"/><input value={form.linkUrl} onChange={e=>setForm({...form,linkUrl:e.target.value})} placeholder="Button URL" className="rounded-2xl bg-stone-100 px-4 py-3 outline-none"/></div><div className="grid grid-cols-2 gap-3"><input type="date" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})} className="rounded-2xl bg-stone-100 px-4 py-3 outline-none"/><input type="date" value={form.endsAt} onChange={e=>setForm({...form,endsAt:e.target.value})} className="rounded-2xl bg-stone-100 px-4 py-3 outline-none"/></div><button className="inline-flex w-fit items-center gap-2 rounded-full bg-stone-950 px-5 py-3 font-semibold text-white"><Plus size={17}/> Publish promotion</button></div></form><div className="grid gap-3">{items.map(item=><article key={item.id} className="rounded-[2rem] bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm text-stone-600">{item.message}</p></div><button onClick={()=>remove(item.id)} className="rounded-full bg-red-50 p-2 text-red-600"><Trash2 size={16}/></button></div><div className="mt-4 flex items-center justify-between"><span className={`rounded-full px-3 py-1 text-xs ${item.isActive?'bg-emerald-50 text-emerald-700':'bg-stone-100 text-stone-500'}`}>{item.isActive?'Active':'Hidden'}</span><button onClick={()=>toggle(item)} className="rounded-full bg-stone-100 px-4 py-2 text-sm font-semibold">{item.isActive?'Hide':'Show'}</button></div></article>)}{!items.length&&<div className="rounded-[2rem] bg-white p-10 text-center text-stone-500">No promotions yet.</div>}</div></div></main>;
}
