import { useEffect, useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { api } from '../../lib/api.js';

export default function AdminTestimonials() {
  const [items, setItems] = useState([]);
  const [form, setForm] = useState({ name:'',quote:'',location:'',rating:5 });
  const [error,setError] = useState('');
  const load=()=>api.get('/admin/testimonials').then(r=>setItems(r.data.testimonials||[]));
  useEffect(()=>{load().catch(e=>setError(e.response?.data?.message||'Could not load testimonials'));},[]);
  const add=async e=>{e.preventDefault();setError('');try{await api.post('/admin/testimonials',{...form,rating:Number(form.rating)});setForm({name:'',quote:'',location:'',rating:5});await load();}catch(err){setError(err.response?.data?.message||'Could not add testimonial');}};
  const remove=async id=>{if(!window.confirm('Delete this testimonial?'))return;try{await api.delete(`/admin/testimonials/${id}`);await load();}catch(err){setError(err.response?.data?.message||'Could not delete testimonial');}};
  return <main className="p-6 lg:p-10"><p className="text-sm uppercase tracking-[0.3em] text-amber-700">Social proof</p><h1 className="font-display text-4xl font-semibold">Testimonials</h1><p className="mt-2 text-stone-600">Add customer feedback and control what appears publicly.</p>{error&&<div className="mt-5 rounded-2xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}<div className="mt-8 grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><form onSubmit={add} className="rounded-[2rem] bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Add testimonial</h2><div className="mt-4 grid gap-3"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Customer name" className="rounded-2xl bg-stone-100 px-4 py-3 outline-none"/><input value={form.location} onChange={e=>setForm({...form,location:e.target.value})} placeholder="Location (optional)" className="rounded-2xl bg-stone-100 px-4 py-3 outline-none"/><select value={form.rating} onChange={e=>setForm({...form,rating:e.target.value})} className="rounded-2xl bg-stone-100 px-4 py-3 outline-none"><option value="5">5 stars</option><option value="4">4 stars</option><option value="3">3 stars</option><option value="2">2 stars</option><option value="1">1 star</option></select><textarea required value={form.quote} onChange={e=>setForm({...form,quote:e.target.value})} placeholder="Customer feedback" className="min-h-36 rounded-2xl bg-stone-100 px-4 py-3 outline-none"/><button className="inline-flex w-fit items-center gap-2 rounded-full bg-stone-950 px-5 py-3 font-semibold text-white"><Plus size={17}/> Add testimonial</button></div></form><div className="grid gap-3">{items.map(item=><article key={item.id} className="rounded-[2rem] bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="font-semibold">{item.name}</p><p className="text-sm text-amber-700">{'★'.repeat(item.rating)}{'☆'.repeat(5-item.rating)}</p></div><button onClick={()=>remove(item.id)} className="rounded-full bg-red-50 p-2 text-red-600"><Trash2 size={16}/></button></div><p className="mt-4 text-stone-700">“{item.quote}”</p>{item.location&&<p className="mt-3 text-xs text-stone-500">{item.location}</p>}</article>)}{!items.length&&<div className="rounded-[2rem] bg-white p-10 text-center text-stone-500">No testimonials yet.</div>}</div></div></main>;
}
